// Generated by CodiumAI

import { Vec } from "$lib/position/vec";
import { describe, it, expect } from "vitest";
import { Box } from "./box";

describe('Box', () => {

    // Box can be instantiated with two Vec objects as arguments
    it('should instantiate Box with two Vec objects as arguments', () => {
      const p1 = new Vec(1, 2);
      const p2 = new Vec(3, 4);
      const box = new Box(p1, p2);
      expect(box.from).toEqual(new Vec(1, 2));
      expect(box.to).toEqual(new Vec(3, 4));
    });

    // Box can be instantiated with two identical Vec objects as arguments
    it('should instantiate Box with two identical Vec objects as arguments', () => {
      const p1 = new Vec(1, 2);
      const p2 = new Vec(1, 2);
      const box = new Box(p1, p2);
      expect(box.from).toEqual(new Vec(1, 2));
      expect(box.to).toEqual(new Vec(1, 2));
    });
});
